### ISSUE TITLE
Initial Types for providers.

### ISSUE THREAD

**Issue by SamuelLHuber** [dtechvision/farcasterkit#10]
# Initial Types

## Highlevel Overview

Make types for things like user data be available in the core where one could just simply import only the types and nothing else to use in their apps to have strong types available for e.g. fetch API calls

## TODOs

- [ ] Add Types for Neynar
- [ ] Add Types for Airstack
- [ ] Add Types for Hub responses
