### ISSUE TITLE
v1.1.0 - Authentication

### ISSUE THREAD

**Issue by SamuelLHuber** [dtechvision/farcasterkit#2]
# Auth

## Highlevel overview

create hooks for easy management of signers (what AuthKit doesn't do at the moment) and pure authentication (e.g. verify sign in with warpcast - which is what AuthKit does)

Make the Neynar and Hub Provider configs and usage like https://docs.farcaster.xyz/auth-kit/auth-kit-provider so it's compatible in that way and the simple sign in with just works liek auth-kit (wrapper?)

and the creation of signers and management gets added per each provider

## New Hooks to create

- createUser() -> expectedto register new User with Optimism contracts and return FID, Signer)
- useWarpcastSigner() -> sign in a user with warpcast (AuthKit) and return a Signer
- useNeynarSigner() -> use Sign in with Neynar to return a Signer

## TODOs:

- [ ] wrap up examples/auth/with-neynar and move the NeynarProvider as well as components directly to Farcaster Kit's package in packages/farcasterkit
- [ ] create a sign in/ signup and auth using just pure hubs as well and bundle that as HubProvider
    - make sure to not duplicate work from https://docs.farcaster.xyz/auth-kit/introduction simply use it as dependency where possible? - note via comment where that is used so we know when debugging
- [ ] each lets the user create a FC account with a wallet, the component/providers just need to be cleaned then added to packages/farcasterkit before the wallet-specific examples can get edited
- [ ] create a subsequent component/edit the FarcasterKitProvider in packages/farcasterkit to allow a user to log in & create a signer with their wallet
- [ ] wrap up examples/auth/with-auth-kit and add the component/provider edits to packages/farcasterkit
- [ ] also in examples/auth - wrap up either with-dynamic, with-privy, or with-rainbowkit TODO: talk with the relevant teams for potential integration
